export const TOPICS = [
  { id: 1,  text: "Is social media doing more harm than good to democracy?",              cat: "Current Affairs" },
  { id: 2,  text: "Should AI development be regulated by governments?",                   cat: "Current Affairs" },
  { id: 3,  text: "Is remote work genuinely the future of employment?",                   cat: "Current Affairs" },
  { id: 4,  text: "Should platforms be held legally responsible for misinformation?",     cat: "Current Affairs" },
  { id: 5,  text: "Is the gig economy exploitative or liberating for workers?",           cat: "Current Affairs" },
  { id: 6,  text: "Has globalisation done more good than harm?",                          cat: "Current Affairs" },
  { id: 7,  text: "Should developed nations pay climate reparations?",                    cat: "Current Affairs" },
  { id: 8,  text: "Is universal basic income a practical solution to unemployment?",      cat: "Current Affairs" },
  { id: 9,  text: "What does it mean to be truly original in the age of the internet?",  cat: "Abstract" },
  { id: 10, text: "Is ambition a virtue or a vice?",                                      cat: "Abstract" },
  { id: 11, text: "Can you be truly happy without being successful?",                     cat: "Abstract" },
  { id: 12, text: "Is silence more powerful than words?",                                 cat: "Abstract" },
  { id: 13, text: "What is the relationship between freedom and responsibility?",         cat: "Abstract" },
  { id: 14, text: "Is failure necessary for growth?",                                     cat: "Abstract" },
  { id: 15, text: "What does it mean to live a good life?",                               cat: "Abstract" },
  { id: 16, text: "Does art have a moral responsibility?",                                cat: "Abstract" },
  { id: 17, text: "Is certainty more dangerous than doubt?",                              cat: "Abstract" },
  { id: 18, text: "Grades do more harm than good to students.",                           cat: "Debate" },
  { id: 19, text: "Cities should ban private cars within city limits.",                   cat: "Debate" },
  { id: 20, text: "Space exploration is a waste of resources.",                           cat: "Debate" },
  { id: 21, text: "Privacy is more important than national security.",                    cat: "Debate" },
  { id: 22, text: "Standardised testing should be abolished.",                            cat: "Debate" },
  { id: 23, text: "Social media influencers have more power than traditional media.",     cat: "Debate" },
  { id: 24, text: "Democracy is overrated as a system of governance.",                    cat: "Debate" },
  { id: 25, text: "The arts deserve as much funding as the sciences.",                    cat: "Debate" },
  { id: 26, text: "Describe a moment that changed how you see the world.",                cat: "Personal" },
  { id: 27, text: "What does courage mean to you, specifically?",                         cat: "Personal" },
  { id: 28, text: "What would you fix about how people relate to each other?",            cat: "Personal" },
  { id: 29, text: "What is one belief you hold that most people around you don't share?", cat: "Personal" },
  { id: 30, text: "What would you do with an unstructured year and no obligations?",      cat: "Personal" },
  { id: 31, text: "What does home mean to you?",                                          cat: "Personal" },
  { id: 32, text: "Who shaped how you think, and how?",                                   cat: "Personal" },
];

export const CATS = ["All", "Current Affairs", "Abstract", "Debate", "Personal"];
